webapp/src/index.js
Reuploaded index.js
Minor Issue - resolved.
=> feat (webapp): Reupload index.js

webapp/package-lock.json, webapp/package.json, webapp/src/components/AdminFunc.jsx, webapp/src/components/AdminLogin.jsx, webapp/src/components/StudentDetails.jsx, webapp/src/components/StudentSignup.jsx, webapp/src/index.js
UG21
Minor changes to  AdminLogin and StudentSignup.
Student details form created for adding personal details and education details.
=> feat (webapp): Student Details Form Created

webapp/src/components/AddUniversity.jsx
UG10
Created university add page
=> feat(webapp): Created university add form

.gitignore, package-lock.json, package.json, webapp/package-lock.json, webapp/package.json, webapp/src/App.tsx, webapp/src/components/AddUniversity.jsx, webapp/src/components/StudentDetails.jsx
Added the option to enter GRE, TOEFL, and IELTS scores for students.
Added the option to enter additional program details.
=> Modified student details form and add university form

webapp/src/components/AddPrograms.jsx, webapp/src/components/AddUniversity.jsx
Closes #45
Added required field wherever necessary
Added dynamic addition of 'add course' fields
=> Modified add program/course form

server/.vscode/launch.json, server/main.go, server/main_test.go
=> feat(api): Setting up Unit Test Framework

webapp/src/components/AdminLogin.jsx, webapp/src/components/Navigation.jsx, webapp/src/components/Navigation_nonMain.jsx, webapp/src/index.js
closes #33 Different navbars for landing and other pages. Changes made in navbar appearance.
=> feat(webapp): Navbar changed

webapp/cypress/integration/AddUniversitySpec.js, webapp/src/components/AddUniversity.jsx
closes #40
Added cypress testing for add university page
Changed the necessary 'matches' condition in add university form
=> Cypress testing for add university page

webapp/public/index.html, webapp/src/components/Anim.tsx, webapp/src/components/Icon.jsx, webapp/src/components/LandingPage.jsx, webapp/src/components/StudentDetails.jsx, webapp/src/index.css, webapp/src/index.js, webapp/src/typings.d.ts
=> Modified landing page

webapp/package-lock.json, webapp/package.json, webapp/src/components/LandingPage.jsx, webapp/src/components/Navigation.jsx, webapp/src/components/Navigation_nonMain.jsx, webapp/src/components/StudentHomePage.jsx, webapp/src/index.js
Created home page for students after log in
Modified navigation bars
=> Created student home page

webapp/src/components/Footerx.jsx, webapp/src/components/Lp.jsx, webapp/src/components/ProfilePage.jsx, webapp/src/components/StudSignUp.jsx, webapp/src/components/landing.css, webapp/src/index.js
=> feat(webapp): created modal sign up page

webapp/src/components/Footerx.jsx, webapp/src/components/Lp.jsx, webapp/src/components/Navigation.jsx, webapp/src/components/Navigation_nonMain.jsx, webapp/src/components/ProfilePage.jsx, webapp/src/components/ProfileSettingsPage.jsx, webapp/src/components/StudentHomePage.jsx, webapp/src/components/landing.css, webapp/src/index.js
Changed color schema to match the landing page
=> Changed color schema

webapp/src/components/StudentHomePage.jsx, webapp/src/components/landing.css
Updated the blog page (student home page) to include dummy recent posts
=> Updated Blog Page

webapp/src/components/Get.jsx, webapp/src/index.js
Updated the Get request reference file Get.jsx
=> updated Get.jsx file

webapp/src/index.js
reverting a minor change made to index.js
=> changed index.js

package-lock.json, package.json, webapp/src/App.js, webapp/src/components/Dashboard.jsx, webapp/src/components/Navigation_nonMain.jsx, webapp/src/index.js
Shifted application tracker to dashboard page
=> Removed hamburger menu

webapp/src/App.js, webapp/src/components/CS.jsx, webapp/src/components/Canada.jsx, webapp/src/components/MBA.jsx, webapp/src/components/Mech.jsx, webapp/src/components/Navigation.jsx, webapp/src/components/Navigation_nonMain.jsx, webapp/src/components/Resources.jsx, webapp/src/components/UK.jsx, webapp/src/components/US.jsx
Created resources pages, dropdown menu and code cleanup
=> feat(webapp):Created resources pages

webapp/src/components/CS.jsx
=> feat(webapp): updates CS.jsx

webapp/src/components/US.jsx
=> feature(webapp): Update US.jsx

webapp/src/components/MBA.jsx
=> feat(webapp):Updates MBA.jsx

webapp/src/components/UK.jsx, webapp/src/components/US.jsx
Updated UK.jsx
Minor changes to US.jsx
=> feature(webapp): Updated UK.jsx

webapp/package-lock.json, webapp/package.json, webapp/src/components/CS.jsx, webapp/src/components/Mech.jsx
=> feat(webapp):Updates CS.jsx

webapp/src/components/CS.jsx, webapp/src/components/MBA.jsx, webapp/src/components/Mech.jsx
Updated mech.jsx along with stickybox, courses resources menu now complete
=> feat(webapp):updates mech.jsx

webapp/src/components/Canada.jsx, webapp/src/components/UK.jsx, webapp/src/components/US.jsx
Updated Canada.jsx
Minor changes to US.jsx and UK.jsx
=> feature(webapp): Updated Canada.jsx

webapp/src/components/CS.jsx, webapp/src/components/Canada.jsx, webapp/src/components/MBA.jsx, webapp/src/components/Mech.jsx, webapp/src/components/UK.jsx, webapp/src/components/US.jsx
Minor changes to US.jsx UK.jsx Canada.jsx CS.jsx Mech.jsx MBA.jsx
closes #121
=> feature(webapp): Minor changes

webapp/src/App.js, webapp/src/components/Explore.jsx, webapp/src/components/Get.jsx, webapp/src/components/Navigation.jsx, webapp/src/components/Resources.jsx, webapp/src/components/landing.css
Created Explore.jsx and deleted Resources.jsx which was no longer used
=> feat(webapp): updates Explore.jsx

webapp/src/App.js, webapp/src/components/Explore.jsx, webapp/src/components/Get.jsx
implements get to show university data dynamically, needs improvement
=> feat(webapp):Updates Explore.js

webapp/src/components/Dashboard.jsx, webapp/src/components/Get.jsx, webapp/src/components/landing.css
User dashboard created to track university applications
=> feature(webapp): Updates Dashboard.jsx

webapp/src/components/StudentHomePage.jsx
validation minor changes, needs improvement
=> Updates StudentHomePage.jsx

webapp/src/components/Explore.jsx, webapp/src/components/Navigation_nonMain.jsx, webapp/src/components/ProfilePage.jsx, webapp/src/components/ProfileSettingsPage.jsx, webapp/src/components/StudentHomePage.jsx
Removed notification and chat icons
Minor changes in other files
=> feature(webapp): Updates Navigation_nonMain.jsx

webapp/src/components/login.jsx
=> feature(webapp): Update login.jsx

webapp/src/components/landingPage.jsx, webapp/src/components/login.jsx
=> feat(webapp): Updates landingPage.jsx

webapp/src/components/studentHomePage.jsx
=> feature(webapp): Update studentHomePage.jsx

webapp/src/components/landing.css, webapp/src/components/profilePage.jsx, webapp/src/components/profileSettingsPage.jsx
=> feature(webapp): Updates profileSettingsPage.jsx

webapp/src/components/profilePage.jsx
=> feature(webapp): Update profilePage.jsx
